CREATE TABLE insert_test_table
(wf_1 TEXT NOT NULL,
wf_2 TEXT ,
wf_3 TEXT ,
wf_4 TEXT ,
wf_5 TEXT ,
wf_6 TEXT ,
wf_7 TEXT ,
wf_8 TEXT ,
wf_9 TEXT ,
wf_10 TEXT ,
wf_11 TEXT ,
wf_12 TEXT ,
wf_13 TEXT ,
wf_14 TEXT ,
wf_15 TEXT ,
wf_16 TEXT ,
column_name BOOLEAN NOT NULL,
time_stamp TIMESTAMP ,
PRIMARY KEY (wf_1));
